# Generated by Django 4.1.5 on 2023-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drooli', '0002_remove_students_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
