# Generated by Django 4.1.5 on 2023-02-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drooli', '0003_students_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=500)),
                ('program_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parents',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='students',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='parents',
            name='_zipcode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='_zipcode',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parents',
            name='phone_work',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_documents',
            name='document_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drooli.programs'),
        ),
    ]
