# Generated by Django 4.1.5 on 2023-02-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drooli', '0004_programs_remove_parents_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_messages',
            old_name='parent',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='parent_messages',
            name='sender',
            field=models.CharField(default='blank', max_length=250),
            preserve_default=False,
        ),
    ]
